spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.155.88.126:3306/uaams?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: Wy-tcl2018!
  devtools:
    restart:
      enabled: true
hello: Hello,the micro-services!